### ISSUE TITLE
Incorrect

### ISSUE THREAD

**Issue by sindresorhus** [kentcdodds/path-here#8]
The readme example and package description mentions `__dirname`, but this module is actually using `process.cwd()`. [`__dirname` and `process.cwd()` are different.](http://stackoverflow.com/questions/9874382/whats-the-difference-between-process-cwd-vs-dirname)

This module:

``` js
var here = require('path-here');
var srcDirectory = here('src');
```

Is pretty much just:

``` js
var path = require('path');
var srcDirectory = path.resolve('src');
```

**Comment by kentcdodds** [comment]
Ah! You're right! I remember now that I originally created this based on a function I had in my projects:

```
function here(p) {
  return path.join(__dirname, p)
}
```

I created that part of the README first, then realized that `__dirname` wouldn't work in a separate module. I'm thinking that this module should probably just be deprecated as it doesn't provide a whole lot of value. Though this is handy:

``` javascript
// specify a different root other than process.cwd()
var there = here.dir('/usr');
var bin = there('bin');
```

Maybe I'll just update the docs with a disclaimer that the default functionality isn't very useful.

**Comment by vith** [comment]
baaf82f missed these mentions of `__dirname` in the npm package metadata:

https://github.com/kentcdodds/path-here/blob/baaf82f2a6e194062e114db3fd5b60b913e7f382/package.json#L3

https://github.com/kentcdodds/path-here/blob/baaf82f2a6e194062e114db3fd5b60b913e7f382/package.json#L20

I was looking for an `import.meta`-based replacement for `__dirname` and took a wrong turn here.
